name: Continuous Delivery
on:  
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: charliecumber/dotnettemplate
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image_name: dotnettemplate
        image_tags: latest,${GITHUB_SHA}

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "frozen-cliffs-45304" 
          heroku_email: "charlie.cumber@softwire.com"
          usedocker: true

