name: Continuous Integration
on:  
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web


  publish_to_registry:
    name: Publish to registry
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: charliecumber/dotnettemplate
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    needs: publish_to_registry
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "frozen-cliffs-45304" 
          heroku_email: "charlie.cumber@softwire.com"
